# -*- coding: utf-8 -*-
"""Club_Cafe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEFGXtqlLT83__zkITT7O5SQdjN0jxI1

#Install Dependacies
"""

!pip install streamlit pyngrok

"""#Website Code"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile club_cafe_app.py
# import streamlit as st
# import sqlite3
# import pandas as pd
# 
# #DATABASE SETUP (Backend & SQL)
# def init_db():
#     conn = sqlite3.connect('cafe_database.db')
#     c = conn.cursor()
#     # Create Orders Table
#     c.execute('''CREATE TABLE IF NOT EXISTS orders
#                  (id INTEGER PRIMARY KEY AUTOINCREMENT,
#                   name TEXT, phone TEXT, item TEXT,
#                   quantity INTEGER, address TEXT, status TEXT)''')
#     # Create Contact Table
#     c.execute('''CREATE TABLE IF NOT EXISTS messages
#                  (id INTEGER PRIMARY KEY AUTOINCREMENT,
#                   name TEXT, email TEXT, message TEXT)''')
#     conn.commit()
#     conn.close()
# 
# def add_order(name, phone, item, quantity, address):
#     conn = sqlite3.connect('cafe_database.db')
#     c = conn.cursor()
#     c.execute("INSERT INTO orders (name, phone, item, quantity, address, status) VALUES (?, ?, ?, ?, ?, ?)",
#               (name, phone, item, quantity, address, 'Pending'))
#     conn.commit()
#     conn.close()
# 
# def add_message(name, email, message):
#     conn = sqlite3.connect('cafe_database.db')
#     c = conn.cursor()
#     c.execute("INSERT INTO messages (name, email, message) VALUES (?, ?, ?)",
#               (name, email, message))
#     conn.commit()
#     conn.close()
# 
# # Initialize DB on first run
# init_db()
# 
# 
# # FRONTEND SETUP (Custom CSS)
# st.set_page_config(page_title="Club Cafe", layout="wide")
# 
# # Custom CSS to satisfy "Frontend: CSS" requirement
# st.markdown("""
#     <style>
#     .main-title {
#         font-size: 50px;
#         font-weight: bold;
#         color: #4A2C2A;
#         text-align: center;
#         font-family: 'Helvetica Neue', sans-serif;
#     }
#     .sub-text {
#         text-align: center;
#         font-size: 20px;
#         color: #666;
#     }
#     .stButton>button {
#         background-color: #4A2C2A;
#         color: white;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # APP NAVIGATION
# st.sidebar.title("☕ Club Cafe")
# page = st.sidebar.radio(
#     "Navigation",
#     ["Home", "Menu", "Online Ordering", "Gallery", "About Us", "Location & Timings", "Reviews", "Contact Us", "Admin Panel"]
# )
# 
# #HOME PAGE
# if page == "Home":
#     st.markdown('<p class="main-title">☕ Welcome to Club Cafe</p>', unsafe_allow_html=True)
#     st.markdown('<p class="sub-text">Delicious Cakes • Cozy Ambience • Sweet Memories</p>', unsafe_allow_html=True)
# 
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col2:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBvX34iHo5vbzPBG0b-vONhyOT5c8waSufPA&s", use_container_width=True)
# 
#     st.write("""
#     **Club Cafe** offers premium cakes, pastries, and desserts made with love.
#     Perfect for birthdays, celebrations, and sweet cravings!
#     """)
# 
# #MENU PAGE
# elif page == "Menu":
#     st.title("🍰 Our Menu")
# 
#     # SIGNATURE CAKES
#     st.subheader("🎂 Signature Cakes")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_5wELZrcZ1U5ThkVVNQsHkYxoZRX0RXII8Q&s", width=300)
#         st.caption("Classic Black Forest")
#     with col2:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT-eW7xysxfcjT0FLUPmjkI16_8IN_VnhfEQ&s", width=300)
#         st.caption("Red Velvet Delight")
#     with col3:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNd9udWKCoXTBYn5ba8reyBDVTTohfOPesng&s", width=300)
#         st.caption("Chocolate Truffle")
# 
#     # PREMIUM DESIGNER CAKES
#     st.subheader("🎨 Premium Designer Cakes")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.image("https://www.indiacakes.com/media/catalog/product/cache/a4577f844569f68fd14659d95bb20f68/a/p/appetizing_ferrero_rocher_cake_1_kg.jpg", width=300)
#         st.caption("Ferrero Rocher Cake")
#     with col2:
#         st.image("https://i0.wp.com/www.darrycakes.com/wp-content/uploads/2019/11/chocolate-oreo-buttercream-cake-25.jpg?fit=1280%2C853&ssl=1", width=300)
#         st.caption("Oreo Crunch Cake")
#     with col3:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH9A1GWpYrfDHFc9F6d0erGWDwSZB63FBihw&s", width=300)
#         st.caption("Blueberry Cheesecake")
# 
#     # CUPCAKES
#     st.subheader("🧁 Cupcakes")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.image("https://bonnibakery.com/wp-content/uploads/2024/03/German-Chocolate-Cupcakes_53-1-1024x1024.jpg.webp", width=300)
#         st.caption("Chocolate Fudge Cupcake")
#     with col2:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0x9TzmB322pvAgqA0a2cXJuP6FwnitYLRIQ&s", width=300)
#         st.caption("Vanilla Sprinkle Cupcake")
#     with col3:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdiiXx7PebgAUz7jgyXGfdXytwnRddVyVftw&s", width=300)
#         st.caption("Red Velvet Cupcake")
# 
#     # PASTRIES
#     st.subheader("🥐 Pastries")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeQU_Kopa9mOkCRMUoqkaj7O0lQN7UTfeBPw&s", width=300)
#         st.caption("Chocolate Pastry")
#     with col2:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToxvsBPUt1uMGVgkW4EF5e0b-Gy48V4xrDgQ&s", width=300)
#         st.caption("Strawberry Pastry")
#     with col3:
#         st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXy67fvOijrYBt7qAW6Tq1R_eW2QUiH-j79g&s", width=300)
#         st.caption("Butterscotch Pastry")
# 
# #ONLINE ORDERING (DATABASE LINKED)
# elif page == "Online Ordering":
#     st.title("🛒 Online Ordering")
#     st.write("Your order will be saved to our database instantly!")
# 
#     with st.form("order_form"):
#         name = st.text_input("Customer Name")
#         phone = st.text_input("Phone Number")
#         item = st.selectbox("Select Item", [
#             "Classic Black Forest", "Red Velvet Delight", "Chocolate Truffle",
#             "Ferrero Rocher Cake", "Oreo Crunch Cake", "Chocolate Fudge Cupcake",
#             "Oreo Cupcake", "Chocolate Pastry", "Strawberry Pastry"
#         ])
#         quantity = st.number_input("Quantity", min_value=1, value=1)
#         address = st.text_area("Delivery Address")
#         submit = st.form_submit_button("Place Order")
# 
#         if submit:
#             if name and phone and address:
#                 # SAVE TO DATABASE
#                 add_order(name, phone, item, quantity, address)
#                 st.success(f"✅ Order placed successfully! Thank you, {name}.")
#                 st.balloons()
#             else:
#                 st.error("Please fill in all details.")
# 
# # GALLERY PAGE
# elif page == "Gallery":
#     st.title("📸 Gallery")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.image("https://images.unsplash.com/photo-1542826438-bd32f43d626f", width=300)
#     with col2:
#         st.image("https://images.unsplash.com/photo-1578985545062-69928b1d9587", width=300)
#     with col3:
#         st.image("https://images.unsplash.com/photo-1551024601-bec78aea704b", width=300)
# 
# # ABOUT US PAGE
# elif page == "About Us":
#     st.title("ℹ️ About Club Cafe")
#     st.write("""
#     At **Club Cafe**, we believe the best ingredients are simple: flour, sugar, butter, and a whole lot of love.
#     What started as a small family kitchen filled with the smell of grandma’s signature cheesecake has grown into the café you see today.
# 
#     We are a family-run bakery dedicated to keeping traditional baking alive. In a world of mass-produced sweets, we choose the slow path.
#     We hand-knead our dough, whip our cream fresh daily, and bake in small batches to ensure every bite tastes just like home.
#     """)
# 
# # LOCATION PAGE
# elif page == "Location & Timings":
#     st.title("📍 Location & Timings")
#     st.markdown("""
#     **📍 Address:** Club Cafe, MG Road, Pune, Maharashtra, India
# 
#     **⏰ Timings:** Monday – Sunday: 10:00 AM – 11:00 PM
#     """)
#     st.map(pd.DataFrame({"lat": [18.5204], "lon": [73.8567]}))
# 
# # REVIEWS PAGE
# elif page == "Reviews":
#     st.title("⭐ Customer Reviews")
#     st.info("⭐⭐⭐⭐⭐ Best cakes in town! – Rahul")
#     st.info("⭐⭐⭐⭐ Loved the Red Velvet cake – Anjali")
#     st.info("⭐⭐⭐⭐⭐ Amazing ambience and taste – Sneha")
#     st.info("⭐⭐⭐⭐⭐ One of the best pastry and cake franchises. The costs are on the higher side but definitely worth the experience. So far, I've tried the Hazelnut chocolate pastry, dutch truffle pastry - Akhil")
# 
# # CONTACT US (DATABASE LINKED)
# elif page == "Contact Us":
#     st.title("📞 Contact Us")
#     st.markdown("**📧 Email:** clubcafe@gmail.com | **📱 Phone:** +91 98765 43210")
# 
#     with st.form("contact_form"):
#         cname = st.text_input("Your Name")
#         cemail = st.text_input("Your Email")
#         message = st.text_area("Message")
#         send = st.form_submit_button("Send Message")
# 
#         if send:
#             if cname and message:
#                 add_message(cname, cemail, message)
#                 st.success("📩 Message sent successfully and saved to database!")
#             else:
#                 st.error("Please fill in your name and message.")
# 
# # ADMIN PANEL (To Verify Database)
# elif page == "Admin Panel":
#     st.title("🔐 Admin Dashboard")
#     st.write("This section is to verify that the Database connection is working.")
# 
#     conn = sqlite3.connect('cafe_database.db')
# 
#     st.subheader("Recent Orders")
#     df_orders = pd.read_sql_query("SELECT * FROM orders", conn)
#     st.dataframe(df_orders)
# 
#     st.subheader("Recent Messages")
#     df_msgs = pd.read_sql_query("SELECT * FROM messages", conn)
#     st.dataframe(df_msgs)
# 
#     conn.close()

"""#API Authentication"""

from google.colab import userdata
from pyngrok import ngrok

# Get ngrok token from Colab Secrets
ngrok_token = userdata.get("NGROK_AUTH_TOKEN")

# Authenticate ngrok
ngrok.set_auth_token(ngrok_token)

print("✅ Ngrok authenticated using Colab Secrets")

"""#Run Streamlite in backgrouwnd"""

!streamlit run club_cafe_app.py --server.port 8501 &

"""#Get URL"""

ngrok.kill()   # clear old tunnels
public_url = ngrok.connect(8501)
public_url